title: Tywen's Technical Blog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Real time learnings from the trenches of my journey from no stack to full stack. This may take a while.

# social links
twitter_username: tywenk # DO NOT include the @ character, or else the build will fail!
github_username:  tywenk # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
